name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ '8' ]
        # java_version: ['8', '11', '17']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
      - name: Run a build and generate the dependency graph which will be submitted post-job
        run: ./gradlew clean build --info
