name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Java ${{ matrix.java_version }} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11', '17', '21']
        os: [ ubuntu-latest ]
        include:
          - java_version: '11'
            os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_ARGS: '--no-transfer-progress'

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Deploy with Maven
        run: mvn -B -Prelease deploy
        if: matrix.java_version == '11' && github.event_name == 'push'
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Build with Maven
        run: mvn -B package
        if: matrix.java_version != '11' || github.event_name != 'push'
